[build]
  publish = "public"
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[build.environment]
  HUGO_VERSION = "0.124.0"   # use the exact version you have locally: `hugo version`
  HUGO_EXTENDED = "true"
