[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.124.0"   # set to your local version: hugo version
  HUGO_EXTENDED = "true"
  GIT_DEPTH= "0"
  GIT_SUBMODULE_STRATEGY = "recursive"  # if your theme is a submodule
  GIT_LFS_ENABLED = "1"                 # if you track big images with LFS

# Strong caching for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
